import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css';
import '@fontsource/inter';
import Navigation from '@/components/layouts/Navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Navigation />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
